### ISSUE TITLE
Repeat frame detection

### ISSUE THREAD

**Issue by tornupnegatives** [tornupnegatives/TMS-Express#3]
## Description

Because the human vocal tract changes rather slowly, it is likely that adjacent Frames are similar enough that they do not each require their own set of parameters. Instead, the first one maintains a full parameter set, and subsequent Frames are marked as repeats and contain only energy and pitch.

## Solution Space

The `FramePostprocessor` should compare the reflector coefficients of all Frames and determine whether or not to classify them as repeats. Criteria must be established to determine what constitutes Frame similarity.

**Comment by deladriere** [comment]
I really want to try this because Bluewizzard and python_wizard don't seem to generate repeat frames

**Comment by tornupnegatives** [comment]
> I really want to try this because Bluewizzard and python_wizard don't seem to generate repeat frames

The feature is live, and you can enable it with the `-r` flag. Please let me know if you like it, and feel free to open a new issue if not. Thanks for your interest in my project :)
