### ISSUE TITLE
Windows Builds?

### ISSUE THREAD

**Issue by eh891l3b** [tornupnegatives/TMS-Express#42]
Hi, are there any plans to include Windows builds in the releases?

**Comment by tornupnegatives** [comment]
Yes, I do plan to include builds for macOS, Linux, and Windows starting with the next release. My original plan to was to produce statically linked binaries for all platforms, but building them automatically appears to be too much for poor GitHub actions to handle...

So, I am looking into providing dynamically linked binaries with the option to install on macOS via Homebrew and Linux via an AppImage. Unfortunately, I do not have a Windows machine nor knowledge of the ecosystem, so I am not sure how best to package up the project.

Off the top of your head, do you know of the most common route for this? Something like Homebrew for Windows, which would let me distribute a dynamic build and specify dependencies to be installed alongside it?

**Comment by tornupnegatives** [comment]
@ElijahHamilton, do you have any experience deploying Qt applications on Windows? I have created some GitHub Actions workflow for macOS and Linux in the [dynamic_builds](https://github.com/tornupnegatives/TMS-Express/tree/dynamic_builds) branch, but I do not know anything about Windows development to do something similar...

The Actions in that branch are able to produce dynamically linked binaries on macOS which resolve dependencies via Homebrew. The Ubuntu action does not quite work yet.

**Comment by tornupnegatives** [comment]
@matteovidali, could you take a look at this as well, please?

**Comment by nonlaminar** [comment]
In terms of the windows build, I have a few suggestions. To generate statically linked binaries, it takes a high amount of resources on this platform. The compilation is generally slow with cmake and nmake, but could possibly be improved by utilizing the Ninja generator option (`cmake -G "Ninja"`) to rather prefer the faster and lighter ninja build system which could allow this to be used in an action (perhaps??). 
In terms of deploying this, I will continue to work on and investigate this issue, but in the mean time, you may checkout [windeployqt](https://doc.qt.io/Qt-5/windows-deployment.html) which can package a QT type application for windows, or make an installation package. There is a [linux equivalent](https://github.com/probonopd/linuxdeployqt) that may be superfluous for this as you already are using the .deb.
I will try and get the installer version working on windows ASAP.

**Comment by tornupnegatives** [comment]
@matteovidali, I just updated the `dynamic_builds` branch to generate builds for Ubuntu using `cqtdeployer`, and it looks like it works pretty well. To my understanding, `cqtdeployer` is also compatible with Windows. Maybe it will work for you too.

**Comment by nonlaminar** [comment]
@tornupnegatives, Great, Ill give that a shot and update you!

**Comment by tornupnegatives** [comment]
@ElijahHamilton, have you tried running the Linux build (see Releases) in Windows Subsystem for Linux?

**Comment by ghost** [comment]
Yes, I have. And it works just fine.
